In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('/content/gurgaon_properties.csv')

In [5]:
df.sample(5)

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2909,2 BHK Flat in Sector 74 Gurgaon,flat,m3m skywalk,1.40,9831.0,1424.0,Super Built up area 1424(132.29 sq.m.),2 Bedrooms,2,2,not available,"2bhk Flat For Sale, Sector 74 Gurgaon, Gurgaon...",17.0,North-East,0 to 1 Year Old,"['Omaxe Gurgaon Mall', 'Omaxe Celebration Mall...",Avl for sale in m3m skywalk 2bhk,"['2 Wardrobe', '4 Fan', '3 Geyser', '6 Light',...","['Centrally Air Conditioned', 'Water purifier'...",NaN
3862,4 BHK Flat in Sector 82 Gurgaon,flat,mapsko casa bella,1.30,6378.0,2038.0,Super Built up area 1960(182.09 sq.m.),4 Bedrooms,4,3+,servant room,"Sector 82 Gurgaon, Gurgaon, Haryana",1.0,North,1 to 5 Year Old,"['Vatika City Centre Mall', 'Pataudi Road', 'B...","Spacious, completely filled society, on main r...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Amenities4 out of ..."
2273,6 Bedroom House for sale in Sector 14 Gurgaon,house,independent,3.50,18088.0,1935.0,Plot area 215(179.77 sq.m.)Built Up area: 214 ...,6,4,2,others,"Sector 14, Sector 14 Gurgaon, Gurgaon, Haryana",2.0,West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...",House for sale plot size 215 sqyard park facin...,"['6 Wardrobe', '10 Fan', '1 Exhaust Fan', '4 G...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1497,1 Bedroom House for sale in Sector 39 Gurgaon,house,independent,0.34,7555.0,450.0,Built Up area: 450 (41.81 sq.m.),1,1,1,not available,"Jharsa Village, Sector 39, Gurgaon, Sector 39 ...",1.0,NaN,undefined,"['Rajiv Chowk Mosque', 'State bank of india AT...",1 bhk independent house for sale in gurgaon. T...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
1918,3 BHK Flat in Sector 70 Gurgaon,flat,krrish florence estate,1.30,5600.0,2321.0,Built Up area: 1865 (173.26 sq.m.),3 Bedrooms,3,3,not available,"Sector 70 Gurgaon, Gurgaon, Haryana",17.0,NaN,Under Construction,"['Omaxe Gurgaon Mall', 'NH248A', 'The Vivekana...",Residential apartment for sell. The property h...,"['4 Wardrobe', '1 Exhaust Fan', '3 Geyser', '5...",NaN,"['Safety3.5 out of 5', 'Lifestyle4 out of 5', ..."

In [6]:
df.shape

(3968, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3968 entries, 0 to 3967
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3968 non-null   object
 1   property_type    3968 non-null   object
 2   society          3967 non-null   object
 3   price            3939 non-null   float64
 4   price_per_sqft   3939 non-null   float64
 5   area             3939 non-null   float64
 6   areaWithType     3968 non-null   object
 7   bedRoom          3968 non-null   object
 8   bathroom         3968 non-null   int64
 9   balcony          3968 non-null   object
 10  additionalRoom   3968 non-null   object
 11  address          3957 non-null   object
 12  floorNum         3947 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3967 non-null   object
 15  nearbyLocations  3755 non-null   object
 16  description      3968 non-null   object
 17  furnishDetails   2931 non-null   object
 18  features         3251 non-null   object
 19  rating           3519 non-null   object
dtypes: float64(4), int64(1), object(15)
memory usage: 620.1+ KB

In [8]:
df.isna().sum()

property_name         0
property_type         0
society               1
price                29
price_per_sqft       29
area                 29
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1184
agePossession         1
nearbyLocations     213
description           0
furnishDetails     1037
features            717
rating              449
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

# extract sector info and making one new column

In [10]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Vishnu Garden,house,independent,0.74,7400.0,1000.0,Built Up area: 1000 (92.9 sq.m.),3,3,0,not available,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",2.0,NaN,undefined,NaN,3bhk residential house for resale in vishnu ga...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,6 BHK Flat in Sector 70 Gurgaon,flat,tulip ivory,5.00,10416.0,4800.0,Carpet area: 4800 (445.93 sq.m.),6 Bedrooms,7,3+,"study room,servant room","Sector 70 Gurgaon, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...",It is new unused property park facing with kit...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area3.5 out of 5', 'Construction3.5 ou..."
2,3 BHK Flat in Sohna,flat,signature global park,0.90,8035.0,1120.0,Super Built up area 1120(104.05 sq.m.),3 Bedrooms,2,2,not available,"Sohna, Gurgaon, Haryana",2.0,South,Dec 2024,"['Sector 55-56 metro', 'Global city centre', '...",We are the proud owners of this 3 bhk apartmen...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,9 Bedroom House for sale in Sector 47 Gurgaon,house,independent,5.15,26615.0,1935.0,Plot area 215(179.77 sq.m.),9,9,3+,store room,"02120, Sector 47 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Corner 9bhk 215sq.Yd east facing independent f...,"['9 Wardrobe', '13 Fan', '1 Exhaust Fan', '23 ...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
4,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley aqua front towers,1.70,9502.0,1789.0,Super Built up area 1789(166.2 sq.m.),3 Bedrooms,3,3,not available,"Sector-33 Sohna, Gurgaon, Haryana",12.0,NaN,Under Construction,"['Taj Hotel & Family Restaurant', 'Signature G...",Residential apartment for sell.Located in sohn...,"['1 Wardrobe', '1 Fan', '1 Light', '2 AC', 'No...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...",NaN

In [11]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [12]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Vishnu Garden,house,independent,Vishnu Garden,0.74,7400.0,1000.0,Built Up area: 1000 (92.9 sq.m.),3,3,0,not available,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",2.0,NaN,undefined,NaN,3bhk residential house for resale in vishnu ga...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,6 BHK Flat in Sector 70 Gurgaon,flat,tulip ivory,Sector 70,5.00,10416.0,4800.0,Carpet area: 4800 (445.93 sq.m.),6 Bedrooms,7,3+,"study room,servant room","Sector 70 Gurgaon, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...",It is new unused property park facing with kit...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area3.5 out of 5', 'Construction3.5 ou..."
2,3 BHK Flat in Sohna,flat,signature global park,Sohna,0.90,8035.0,1120.0,Super Built up area 1120(104.05 sq.m.),3 Bedrooms,2,2,not available,"Sohna, Gurgaon, Haryana",2.0,South,Dec 2024,"['Sector 55-56 metro', 'Global city centre', '...",We are the proud owners of this 3 bhk apartmen...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,9 Bedroom House for sale in Sector 47 Gurgaon,house,independent,Sector 47,5.15,26615.0,1935.0,Plot area 215(179.77 sq.m.),9,9,3+,store room,"02120, Sector 47 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Corner 9bhk 215sq.Yd east facing independent f...,"['9 Wardrobe', '13 Fan', '1 Exhaust Fan', '23 ...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
4,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley aqua front towers,Sector-33 Sohna,1.70,9502.0,1789.0,Super Built up area 1789(166.2 sq.m.),3 Bedrooms,3,3,not available,"Sector-33 Sohna, Gurgaon, Haryana",12.0,NaN,Under Construction,"['Taj Hotel & Family Restaurant', 'Signature G...",Residential apartment for sell.Located in sohn...,"['1 Wardrobe', '1 Fan', '1 Light', '2 AC', 'No...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...",NaN

In [13]:

df['sector'] = df['sector'].str.lower()

In [14]:
df.head(2)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Vishnu Garden,house,independent,vishnu garden,0.74,7400.0,1000.0,Built Up area: 1000 (92.9 sq.m.),3,3,0,not available,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",2.0,NaN,undefined,NaN,3bhk residential house for resale in vishnu ga...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,6 BHK Flat in Sector 70 Gurgaon,flat,tulip ivory,sector 70,5.00,10416.0,4800.0,Carpet area: 4800 (445.93 sq.m.),6 Bedrooms,7,3+,"study room,servant room","Sector 70 Gurgaon, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...",It is new unused property park facing with kit...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area3.5 out of 5', 'Construction3.5 ou..."

In [15]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 81                                                     90
sector 65                                                     90
sector 90                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 56                                                     57
sector 95                                                     57
sector 89                                                     56
sector 48                                                     56
sector 70a                                                    54
sector 37c                                                    53
nirvana country                                               53
sector 70                                                     53
sector 84                                                     51
sector-33 sohna                                               51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 1                                                   43
dlf phase 2                                                   43
sector 113                                                    43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
laxman vihar                                                  29
sector 72                                                     29
sector 54                                                     27
sector 71                                                     27
dlf phase 4                                                   25
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
dlf phase 3                                                   22
sector 67a                                                    22
sector 111                                                    22
sector 82a                                                    20
sector 22                                                     20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 62                                                     17
sector 91                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
rajendra park                                                 15
sector 14                                                     15
sector 63                                                     15
sector 60                                                     15
sector 3                                                      14
sector 52                                                     14
sector 1 imt manesar                                          14
sector 76                                                     14
gwal pahari                                                   14
sector 53                                                     14
dlf phase 5                                                   14
sector 36a                                                    13
sector 46                                                     13
laxman vihar phase 2                                          13
sector 50                                                     12
sector 31                                                     12
sector 39                                                     12
sector 38                                                     12
uppals southend                                               12
sohna road                                                    12
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 93                                                     11
sector 9a                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 95a                                                     9
ashok vihar phase 2                                            9
south city 1                                                   9
sector 4                                                       9
sector 55                                                      9
sector 40                                                      8
malibu town                                                    8
sector 57                                                      8
sector 89 a                                                    8
sector 10a                                                     8
sector 59                                                      8
sector 43                                                      8
c block sushant lok phase 1                                    8
palam vihar extension                                          8
dwarka expressway                                              8
mehrauli  road                                                 8
new colony                                                     7
mianwali colony                                                7
sector 58                                                      7
sector 36 sohna                                                7
sector 51                                                      7
sector 26                                                      7
surat nagar 1                                                  7
sector 11                                                      7
ansal plaza                                                    6
jacobpura                                                      6
jyoti park                                                     6
rajiv nagar                                                    6
sector 1                                                       6
ashok vihar                                                    6
sector 5                                                       6
sector 105                                                     5
sector 30                                                      5
manesar                                                        5
subhash nagar                                                  5
madanpuri                                                      5
sector 80                                                      5
sector 28                                                      5
dharam colony                                                  5
sector 23a                                                     5
chakkarpur                                                     5
sector 9                                                       5
dayanand colony                                                5
greenwood city                                                 5
sushant lok phase 2                                            5
sector 2                                                       5
new palam vihar                                                5
saraswati vihar                                                5
arjun nagar                                                    5
surya vihar                                                    4
sector 12a                                                     4
sector 3a                                                      4
sector 12                                                      4
sector 45                                                      4
shivpuri                                                       4
suncity                                                        4
new                                                            4
sector 8                                                       4
adarsh nagar                                                   4
imt manesar                                                    4
vishnu garden                                                  4
valley view estate                                             4
sector 17                                                      4
ravi nagar                                                     4
shivaji nagar                                                  4
devilal colony                                                 4
garhi harsaru                                                  4
baldev nagar                                                   4
bhondsi                                                        4
sector 36                                                      4
sector 6                                                       4
krishna colony                                                 4
bhim nagar                                                     4
a block sushant lok phase 1                                    3
sector 73                                                      3
mg road                                                        3
sector 88b                                                     3
sector 17b                                                     3
surat nagar                                                    3
shakti nagar                                                   3
maruti kunj                                                    3
sector 17a                                                     3
b block sushant lok phase 1                                    3
sector 23                                                      3
patel nagar                                                    3
gandhi nagar                                                   3
sector 110 a                                                   3
laxmi garden                                                   3
sheetla colony                                                 3
sector 15                                                      3
sector 27                                                      3
prem nagar                                                     3
west rajiv nagar                                               2
iffco chowk                                                    2
sector-11 sohna                                                2
ambience island                                                2
sector 21                                                      2
hira nagar                                                     2
new palam vihar phase 1                                        2
bhawani enclave                                                2
sector 24                                                      2
, delhi ncr                                                    2
samaspur                                                       2
block a surya vihar                                            2
faridabad road                                                 2
sector 15 part 2                                               2
surat nagar phase 2                                            2
mohan nagar                                                    2
manohar nagar                                                  2
farukhnagar                                                    2
acharya puri                                                   2
daulatabad                                                     2
rajiv chowk                                                    2
sushant lok                                                    2
mayfield garden                                                2
shanti nagar                                                   2
new basti                                                      2
golf course ext road                                           2
rosewood                                                       2
sohna  road                                                    2
lajpat nagar                                                   2
sector 32                                                      2
shankar vihar                                                  2
golf course road                                               2
sector 15 part 1                                               2
sector-2 sohna                                                 2
sispal vihar                                                   2
sector 41                                                      2
new palam vihar phase 2                                        2
nars                                                           2
bissar                                                         2
udyog vihar phase 1                                            1
civil l                                                        1
begampur khatola                                               1
hno 13 sagar enclave sura                                      1
saraswati enclave                                              1
near khandsa road                                              1
near sector 1 market                                           1
old delhi road, opp sector-14                                  1
pratap nagar                                                   1
mahalaxmi garden, rajendra place                               1
sec 3 bhim vihar part 1 bhimgher kheri                         1
part 3 sector 5                                                1
near euro                                                      1
huda saraswati vihar                                           1
damdma                                                         1
new colony, sector 7                                           1
bhimgarh kheri phase 3                                         1
sector 21a faridabad                                           1
garauli kalan                                                  1
naharpur rupa                                                  1
gopal nagar, garhi ghasita, sonipat                            1
dhankot                                                        1
v block dlf phase 3                                            1
sector-7 hous                                                  1
ram nagar                                                      1
vir nagar                                                      1
bptp                                                           1
sector 9b                                                      1
mahavir pura                                                   1
ravi nager basai road                                          1
sector 42                                                      1
lucknow                                                        1
devi lal colony gali no 12 gurgaon nr omkar public school      1
urban estate, sector 5                                         1
hsiidc plot sector 1 imt manesar                               1
sector 37a                                                     1
jat colony,fazilpur/taj nagar road                             1
park view                                                      1
kheri                                                          1
rajiv colony                                                   1
dharam colony block e                                          1
sector 5 chowk                                                 1
kanahi                                                         1
om nagar                                                       1
jacobpura near sadar bazar                                     1
khandsa                                                        1
block g sector-57                                              1
ashok vihar phase 3                                            1
saroop garden rajendra park                                    1
bhora kalan                                                    1
laxmna vihar, phase 2                                          1
new jyoti park                                                 1
ashok vihar phase i                                            1
sector 17c                                                     1
south city                                                     1
anand garden, sector-105                                       1
sadar bazar                                                    1
laxman vihar, railway road,                                    1
sultanpur                                                      1
tekchand nagar                                                 1
ansal's palam vihar                                            1
sector 13                                                      1
b1 block sector 57                                             1
sector-35 sohna                                                1
rattan garden                                                  1
heritage city                                                  1
pataudi road                                                   1
near pataudi chowk                                             1
godrej aria , sector 79 ,                                      1
shivji park colony                                             1
sector-5 sheetla colony                                        1
g block dlf city phase 1                                       1
sector 4 urban estate                                          1
sector 37b                                                     1
near nand hospital                                             1
sai kunj                                                       1
ats marigold                                                   1
nirvana country pocket h                                       1
sector-5 sohna                                                 1
alipur                                                         1
cyber city                                                     1
carterpuri village                                             1
block h ashok vihar phase iii extension                        1
Name: count, dtype: int64

### filling sector information manually

In [16]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [17]:

df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [18]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [19]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [20]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [21]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [22]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [24]:
df.head(5)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 Bedroom House for sale in Vishnu Garden,house,independent,sector 105,0.74,7400.0,1000.0,Built Up area: 1000 (92.9 sq.m.),3,3,0,not available,"Vishnu Garden, Sector 105, Vishnu Garden, Gurg...",2.0,NaN,undefined,NaN,3bhk residential house for resale in vishnu ga...,NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
1,6 BHK Flat in Sector 70 Gurgaon,flat,tulip ivory,sector 70,5.00,10416.0,4800.0,Carpet area: 4800 (445.93 sq.m.),6 Bedrooms,7,3+,"study room,servant room","Sector 70 Gurgaon, Gurgaon, Haryana",0.0,NaN,1 to 5 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...",It is new unused property park facing with kit...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area3.5 out of 5', 'Construction3.5 ou..."
2,3 BHK Flat in Sohna,flat,signature global park,sohna road,0.90,8035.0,1120.0,Super Built up area 1120(104.05 sq.m.),3 Bedrooms,2,2,not available,"Sohna, Gurgaon, Haryana",2.0,South,Dec 2024,"['Sector 55-56 metro', 'Global city centre', '...",We are the proud owners of this 3 bhk apartmen...,[],"['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Amenities5 out of 5'..."
3,9 Bedroom House for sale in Sector 47 Gurgaon,house,independent,sector 47,5.15,26615.0,1935.0,Plot area 215(179.77 sq.m.),9,9,3+,store room,"02120, Sector 47 Gurgaon, Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Standard chartered ATM', 'Icici bank ATM', '...",Corner 9bhk 215sq.Yd east facing independent f...,"['9 Wardrobe', '13 Fan', '1 Exhaust Fan', '23 ...","['High Ceiling Height', 'Maintenance Staff', '...","['Environment5 out of 5', 'Lifestyle4.5 out of..."
4,3 BHK Flat in Sector-33 Sohna,flat,central park flower valley aqua front towers,sector-33 sohna road,1.70,9502.0,1789.0,Super Built up area 1789(166.2 sq.m.),3 Bedrooms,3,3,not available,"Sector-33 Sohna, Gurgaon, Haryana",12.0,NaN,Under Construction,"['Taj Hotel & Family Restaurant', 'Signature G...",Residential apartment for sell.Located in sohn...,"['1 Wardrobe', '1 Fan', '1 Light', '2 AC', 'No...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...",NaN

In [29]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [30]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 65                      90
sector 90                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 43                      53
sector 70                      53
sector 37c                     53
sector 84                      51
sector-33 sohna road           51
sector 26                      50
sector 67                      48
sector 49                      48
sector 66                      46
sector 28                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       40
sector 106                     38
sector 4                       38
sector 99a                     32
sector 54                      31
sector 12                      31
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 105                     24
sector 24                      24
sector 57                      24
sector 112                     24
sector 88a                     23
sector 14                      23
sector 33                      23
sector 111                     22
sector 67a                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 3                       20
sector 47                      19
sector 78                      19
sector 63a                     18
gwal pahari                    18
sector 74                      18
sector 91                      17
sector 62                      17
sector 110                     16
sector 99                      16
sector 60                      15
sector 63                      15
sector 55                      14
sector 52                      14
sector 1 manesar               14
sector 53                      14
sector 76                      14
sector 46                      13
sector 6                       13
sector 9                       13
sector 4 phase 2               13
sector 36a                     13
sector 39                      12
sector 38                      12
sector 31                      12
sohna road road                12
sector 93                      11
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 1a manesar              10
sector 13                      10
manesar                         9
sector 3 phase 2                9
sector 23                       9
sector 45                       9
sector 8                        9
sector 95a                      9
dwarka expressway               8
sector 17                       8
sector 59                       8
sector 40                       8
sector 2 extension              8
sector 89 a                     8
c block sector 43               8
sector 10a                      8
sector 36 sohna road            7
sector 51                       7
sector 58                       7
sector 5                        6
sector 1                        6
sector 21                       6
new sector 2                    5
sector 23a                      5
sector 80                       5
sector 30                       5
new                             4
sector 36                       4
sector 3a                       4
sector 12a                      4
b block sector 43               3
patel nagar                     3
sheetla colony                  3
sector 27                       3
sector 15                       3
maruti kunj                     3
sector 17a                      3
sector 110 a                    3
sector 88b                      3
surat nagar                     3
sector 17b                      3
sector 73                       3
a block sector 43               3
Name: count, dtype: int64

In [31]:
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('surat nagar','sector 104')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 67')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','sector 1')

In [33]:
df['sector'] = df['sector'].str.replace('sector 3 phase 3 extension','sector 3')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('sector 1a manesar','sector 1a')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')

In [34]:
df['sector'].value_counts()

sector
sohna road              175
sector 102              113
sector 85               110
sector 92               104
sector 69                94
sector 90                90
sector 65                90
sector 81                90
sector 109               88
sector 79                80
sector 104               76
sector 33                74
sector 83                69
sector 37d               68
sector 86                67
sector 50                65
sector 43                64
sector 107               60
sector 108               59
sector 95                57
sector 56                57
sector 48                56
sector 89                56
sector 2                 55
sector 70a               54
sector 37c               53
sector 70                53
sector 84                51
sector 4                 51
sector 67                51
sector 26                50
sector 49                48
sector 66                46
sector 28                46
sector 103               45
sector 113               43
sector 25                43
sector 82                42
sector 61                42
sector 7                 40
sector 106               38
sector 99a               32
sector 54                31
sector 3                 31
sector 12                31
sector 68                30
sector 72                29
sector 77                29
sector 71                27
sector 105               24
sector 57                24
sector 112               24
sector 24                24
sector 14                23
sector 88a               23
sector 111               22
sector 67a               22
sector 11                21
sector 22                20
sector 1                 20
sector 82a               20
sector 47                19
sector 78                19
gwal pahari              18
sector 74                18
sector 63a               18
sector 91                17
sector 62                17
sector 110               16
sector 99                16
sector 60                15
sector 63                15
sector 53                14
sector 52                14
sector 76                14
sector 55                14
sector 9                 13
sector 46                13
sector 6                 13
sector 36a               13
sector 39                12
sector 31                12
sector 38                12
sector 93                11
sector 41                11
sector 9a                11
sector 1a                10
sector 13                10
sector 95a                9
sector 45                 9
sector 3 phase 2          9
manesar                   9
sector 23                 9
sector 8                  9
sector 17                 8
dwarka expressway         8
sector 59                 8
sector 40                 8
sector 2 extension        8
sector 10a                8
sector 89 a               8
sector 36 sohna road      7
sector 51                 7
sector 58                 7
sector 21                 6
sector 5                  6
new sector 2              5
sector 80                 5
sector 30                 5
sector 23a                5
sector 12a                4
sector 3a                 4
sector 36                 4
new                       4
patel nagar               3
b block sector 43         3
sector 27                 3
sheetla colony            3
sector 15                 3
sector 110 a              3
sector 17a                3
sector 88b                3
sector 17b                3
sector 73                 3
Name: count, dtype: int64

In [35]:
df.sample(10)

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2568,4 Bedroom House for sale in Sector 50 Gurgaon,house,ss hibiscus,sector 50,12.50,40850.0,3060.0,Plot area 470(392.98 sq.m.)Built Up area: 410 ...,4,4,3+,"servant room,study room","Sector 50 Gurgaon, Gurgaon, Haryana",2.0,West,1 to 5 Year Old,"['Baani Square', 'SS Plaza', 'Good Earth City ...",For sale 4 bhk villa in the hibiscus gurgaon. ...,"['1 Water Purifier', '5 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3145,5 Bedroom House for sale in Sector 73 Gurgaon,house,dlf alameda,sector 73,17.00,35109.0,4842.0,Plot area 4842(449.84 sq.m.)Built Up area: 900...,5,8,3,"study room,pooja room,servant room,store room","Alameda, Sector 73 Gurgaon, Gurgaon, Haryana",3.0,North-West,1 to 5 Year Old,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...",It is a tastefully made villa with best of des...,"['1 Water Purifier', '1 Fan', '1 Fridge', '1 E...","['Feng Shui / Vaastu Compliant', 'Private Gard...",NaN
1728,2 BHK Flat in Sector 68 Gurgaon,flat,pareena mi casa,sector 68,1.10,9020.0,1220.0,Super Built up area 1245(115.66 sq.m.)Carpet a...,2 Bedrooms,2,3,not available,"1302, Tower - 3, Sector 68 Gurgaon, Gurgaon, H...",13.0,East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Airia Mall', '...",Residential apartment for sale in prominent lo...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3029,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,sector 107,1.32,6330.0,2085.0,Super Built up area 1943(180.51 sq.m.),3 Bedrooms,3,3,not available,"N/a, Sector 107 Gurgaon, Gurgaon, Haryana",10.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",M3m woodshire is one of gurgaon's most sought ...,[],"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area4.5 out of 5', 'Construction5 out ..."
934,4 BHK Flat in Sector 92 Gurgaon,flat,sare homes,sector 92,0.95,4750.0,2000.0,Super Built up area 2000(185.81 sq.m.)Built Up...,4 Bedrooms,3,2,not available,"Flat T04-1701 Sare Homes Sector 92 Gurgaon, Se...",17.0,East,0 to 1 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",Registry done. Noc given by govt agencies afte...,"['1 Water Purifier', '1 Exhaust Fan', '1 Modul...","['Water purifier', 'Waste Disposal']","['Safety3 out of 5', 'Lifestyle4 out of 5', 'E..."
2744,7 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 2,sector 109,9.50,26389.0,3600.0,Plot area 400(334.45 sq.m.),7,6,3,"pooja room,study room,servant room","332, Sector 109 Gurgaon, Gurgaon, Haryana",3.0,West,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Pacific D2...","Peaceful, private, premium, gated, duplex vill...",NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
237,3 BHK Flat in Sector 36 Sohna,flat,signature global park 4,sector 36 sohna road,1.00,9900.0,1010.0,Carpet area: 1010 (93.83 sq.m.),3 Bedrooms,2,3,not available,"Sector 36 Sohna, Gurgaon, Haryana",2.0,NaN,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'The Leaf Mall ...",Pristine location near the commercial sector o...,"['3 Wardrobe', '4 Fan', '7 Light', '1 Modular ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1257,5 Bedroom House for sale in Sushant Lok Phase 1,house,independent,sector 43,9.50,42222.0,2250.0,Plot area 302(252.51 sq.m.)Built Up area: 300 ...,5,5,3+,"servant room,pooja room","Sushant Lok 1, Sushant Lok Phase 1, Gurgaon, H...",2.0,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'New Life C...","Sushant lok 1 very prime location , this kothi...","['1 Water Purifier', '6 Fan', '1 Exhaust Fan',...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
1047,2 BHK Flat in Sector 102 Gurgaon,flat,suncity avenue,sector 102,0.48,9022.0,532.0,Super Built up area 632(58.71 sq.m.)Carpet are...,2 Bedrooms,2,1,store room,"5th, Sector 102 Gurgaon, Gurgaon, Haryana",5.0,North-East,1 to 5 Year Old,"['The Hive', 'JMS Marine Square', 'Gurugram Rd...",Looking for a 2 bhk property for sale in gurga...,"['3 Fan', '10 Light', 'No AC', 'No Bed', 'No C...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
2413,3 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,sector 102,2.00,10799.0,1852.0,Super Built up area 1852(172.06 sq.m.),3 Bedrooms,3,3,not available,"Sector 102 Gurgaon, Gurgaon, Haryana",9.0,South-East,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Best amenities and best construction quality. ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."

In [36]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [37]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
265,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4 Bedrooms,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun 2027,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2243,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2 Bedrooms,2,1,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2384,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4 Bedrooms,4,3,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3153,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2 Bedrooms,2,2,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [38]:
df.loc[3153,'sector'] = 'sector 37'
df.loc[2384,'sector'] = 'sector 92'
df.loc[2243,'sector'] = 'sector 90'
df.loc[265,'sector'] = 'sector 76'

In [39]:

df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
248,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2 Bedrooms,2,1,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2732,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."
2828,3 Bedroom House for sale in New Palam Vihar,house,independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3290,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,not available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3507,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2 Bedrooms,2,2,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."

In [40]:
df.loc[[248,2732,2828,3290,3507],'sector'] = 'sector 110'

In [41]:
df['sector'].value_counts()

sector
sohna road           175
sector 102           113
sector 85            110
sector 92            105
sector 69             94
sector 90             91
sector 81             90
sector 65             90
sector 109            88
sector 79             80
sector 104            76
sector 33             74
sector 83             69
sector 37d            68
sector 43             67
sector 86             67
sector 95             66
sector 50             65
sector 89             64
sector 2              63
sector 107            60
sector 108            59
sector 56             57
sector 48             56
sector 70a            54
sector 70             53
sector 37c            53
sector 4              51
sector 67             51
sector 84             51
sector 26             50
sector 49             48
sector 28             46
sector 66             46
sector 103            45
sector 113            43
sector 25             43
sector 61             42
sector 82             42
sector 7              40
sector 106            38
sector 3              35
sector 12             35
sector 99a            32
sector 54             31
sector 68             30
sector 72             29
sector 77             29
sector 71             27
sector 112            24
sector 110            24
sector 105            24
sector 24             24
sector 57             24
sector 88a            23
sector 14             23
sector 67a            22
sector 111            22
sector 11             21
sector 22             20
sector 82a            20
sector 1              20
sector 47             19
sector 78             19
gwal pahari           18
sector 63a            18
sector 74             18
sector 62             17
sector 91             17
sector 99             16
sector 76             15
sector 63             15
sector 60             15
sector 23             14
sector 53             14
sector 55             14
sector 52             14
sector 36a            13
sector 46             13
sector 9              13
sector 6              13
sector 31             12
sector 38             12
sector 39             12
sector 36             11
sector 9a             11
sector 41             11
sector 93             11
sector 13             10
sector 1a             10
sector 3 phase 2       9
sector 45              9
manesar                9
sector 8               9
sector 59              8
dwarka expressway      8
sector 17              8
sector 10a             8
sector 40              8
sector 58              7
sector 51              7
sector 5               6
sector 21              6
sector 15              6
sector 80              5
sector 30              5
sector 27              3
sheetla colony         3
sector 17a             3
sector 88b             3
sector 17b             3
sector 73              3
sector 37              1
Name: count, dtype: int64

In [42]:
df.shape

(3814, 21)

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
# Droping unwanted columns -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [46]:
df.sample(10)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1570,flat,godrej aria,sector 79,1.10,11482.0,958.0,Super Built up area 89,2 Bedrooms,2,3,not available,9.0,NaN,0 to 1 Year Old,"['Sapphire 83 Mall', 'Delhi Jaipur Expressway'...",[],NaN
1601,flat,ss the leaf,sector 85,1.22,13318.0,916.0,Super Built up area 1772(164.62 sq.m.)Built Up...,2 Bedrooms,2,3,store room,16.0,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['4 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Intercom Facility', 'Lift(s)', 'High Ceiling..."
1612,flat,dlf the skycourt,sector 86,1.56,8087.0,1929.0,Super Built up area 1929(179.21 sq.m.)Built Up...,3 Bedrooms,4,3+,store room,17.0,South-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",NaN,"['Centrally Air Conditioned', 'Water purifier'..."
1520,house,independent,sector 14,7.50,16600.0,4518.0,Plot area 502(419.74 sq.m.),3,3,2,"pooja room,study room,servant room",1.0,West,10+ Year Old,"['Sheetla Mata Mandir', 'Hsbc bank ATM', 'Hdfc...","['7 Wardrobe', '6 Fan', '1 Exhaust Fan', '3 Ge...","['Maintenance Staff', 'Water Storage', 'Visito..."
1328,house,independent,sector 7,0.89,18658.0,477.0,Plot area 477(44.31 sq.m.),5,3,2,not available,2.0,East,10+ Year Old,"['Geeta Nursing Home Gurgaon', 'Chiranjiv Hosp...",[],['Park']
1748,house,ansal sushant lok,sector 43,10.50,27911.0,3762.0,Plot area 418(349.5 sq.m.),4,4,2,servant room,NaN,North-East,10+ Year Old,"['Huda city centre metro station', 'New Life C...","['6 Fan', '6 Light', 'No AC', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
865,flat,shree arihant apartment,sector 54,1.55,7380.0,2100.0,Super Built up area 2100(195.1 sq.m.)Built Up ...,3 Bedrooms,3,3+,"pooja room,others",3.0,North-East,5 to 10 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","['4 Fan', '1 Exhaust Fan', '4 Geyser', '24 Lig...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
3613,flat,ashiana mulberry,sohna road,0.74,6200.0,1194.0,Carpet area: 1210 (112.41 sq.m.),2 Bedrooms,2,3+,not available,12.0,North-West,0 to 1 Year Old,"['Discount Department Store', 'Badshahpur Sohn...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Intercom Facility',..."
1362,flat,vatika the seven lamps,sector 82,0.78,5932.0,1315.0,Super Built up area 1298(120.59 sq.m.),2 Bedrooms,2,2,not available,0.0,North-West,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","['1 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
927,flat,dlf the skycourt,sector 86,1.50,7894.0,1900.0,Super Built up area 1900(176.52 sq.m.),3 Bedrooms,3,1,others,16.0,East,1 to 5 Year Old,"['Sapphire 83 Mall', 'NH-8, Imt Manesar', 'Rao...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F..."

In [49]:
df.to_csv('gurgaon_properties_cleaned_1.csv',index=False)