# üî¥ why this model needed


## Real-World Example: Meet Rohan

> Rohan is a 28-year-old software engineer working in Gurgaon.
> He is looking to buy a flat near Dwarka Expressway with the intention of renting it out to tenants(kirayedar).

---

###  Flat Details Rohan Finds on 99acres:

* **Property Price:** ‚Çπ1.2 Crore
* **Location:** Sector 102, Dwarka Expressway
* **Property Type:** 3 BHK Flat
* **Expected Rent:** ‚Çπ32,000/month *(based on similar listings)*
* **Down Payment:** 20% = ‚Çπ24 Lakh
* **Home Loan:** ‚Çπ96 Lakh at 7.5% interest for 20 years
* **Other Yearly Costs:**

  * Maintenance: ‚Çπ36,000/year
  * Property Tax: ‚Çπ12,000
  * Insurance + Misc: ‚Çπ6,000

---

## Without the Model: Rohan Thinks‚Ä¶

> ‚ÄúI'll earn ‚Çπ32,000 rent every month = ‚Çπ3.84 lakh/year.
> That‚Äôs great income!‚Äù

But he **doesn't realize** that EMI + taxes + repairs will eat most of it.

---

## With Your ROI Model, He Sees:

| **Calculation**                      | **Value**                                       |
| ------------------------------------ | ----------------------------------------------- |
| EMI (monthly)                        | ‚Çπ77,459                                         |
| Annual EMI                           | ‚Çπ9.29 lakh                                      |
| Rent Income                          | ‚Çπ3.84 lakh/year                                 |
| Total Annual Expenses (EMI + others) | ‚Çπ9.29L + ‚Çπ0.54L = ‚Çπ9.83L                        |
| **Annual Cash Flow**                 | ‚Çπ3.84L - ‚Çπ9.83L = **-‚Çπ5.99L**                   |
| **ROI**                              | Negative (losing ‚Çπ6L/year on ‚Çπ24L down payment) |

# üî¥ So your model warns:
> ‚ÄúRohan, you‚Äôll lose ‚Çπ6L every year if you buy this for rent.‚Äù

---

## What Your Model Helps Rohan Do:

* Try another flat in a **lower price range (‚Çπ80L)**
* Adjust rent, down payment, interest ‚Äî and see which combo gives **positive ROI**
* Choose a property with **best return on investment** ‚Äî like a bank FD!

---

In [1]:
import numpy as np
import pandas as pd

In [69]:
df = pd.read_csv('/content/gurgaon_properties_post_feature_selection_v2.csv')
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor

In [ ]:

'''
Term                                    	What It Means	                    Example (‚Çπ1 Cr property)

Property Price                       	Total cost to buy                         	‚Çπ1 Cr
Down Payment                         	Your upfront payment                      	‚Çπ20 Lakh
EMI	                                  Monthly loan payment	                   ‚Çπ64k/month for 20 years
Annual Rent                     	What tenant pays you in a year	                 ‚Çπ3 Lakh
Gross Yield	                          Rent √∑ Price (%)	                            3%
Expenses                      	Maintenance, tax, insurance, etc.             	‚Çπ50,000/year
Occupancy                         	% of the year rented                          	90%
Net Rent                        	Adjusted rent after expenses                  	‚Çπ2.2 Lakh
Cash Flow                             	Net Rent ‚Äì EMI                    	Negative if EMI > rent
ROI	                              Return on your investment                 	~10.7% (if no EMI)

'''

# EMI = P √ó r √ó (1+r)^n / ((1+r)^n ‚Äì 1)  -----> P: Loan amount,  r: Monthly interest rate,  n: Number of months
# Gross Yield = (Annual Rent / Property Price) √ó 100
# Net Rent = (Annual Rent √ó Occupancy) ‚Äì Expenses
# ROI = (Annual Cash Flow / Total Investment) √ó 100

In [70]:
df['price_rupees'] = df['price'] * 1e7

In [71]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,price_rupees
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor,8200000.0
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor,9500000.0
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor,3200000.0
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor,16000000.0
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor,4800000.0

In [72]:
# Rental yield (% of property value per year)
df['yield_pct'] = np.where(df['price'] < 80e5, 1.8,
                    np.where(df['price'] < 2e7, 2.5,
                             3.2))

In [73]:
# Occupancy rate (%)
df['occupancy_rate'] = np.where(df['price'] < 80e5, 82,
                         np.where(df['price'] < 2e7, 87,
                                  90))

In [74]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,price_rupees,yield_pct,occupancy_rate
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor,8200000.0,1.8,82
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor,9500000.0,1.8,82
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor,3200000.0,1.8,82
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor,16000000.0,1.8,82
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor,4800000.0,1.8,82

In [75]:

# Maintenance rate (rupees per sq ft per month)
df['maint_rate'] = np.where(df['price'] < 80e5, 4,
                     np.where(df['price'] < 2e7, 6,
                              8))

In [76]:
# Property tax rate (% of property value per year)
df['tax_rate_pct'] = np.where(df['price'] < 80e5, 0.2,
                       np.where(df['price'] < 2e7, 0.25,
                                0.3))

In [77]:
df.head()

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,furnishing_type,luxury_category,floor_category,price_rupees,yield_pct,occupancy_rate,maint_rate,tax_rate_pct
0,flat,sector 36,0.82,3.0,2.0,2,New Property,850.0,0.0,0.0,0.0,Low,Low Floor,8200000.0,1.8,82,4,0.2
1,flat,sector 89,0.95,2.0,2.0,2,New Property,1226.0,1.0,0.0,0.0,Low,Mid Floor,9500000.0,1.8,82,4,0.2
2,flat,sohna road,0.32,2.0,2.0,1,New Property,1000.0,0.0,0.0,0.0,Low,High Floor,3200000.0,1.8,82,4,0.2
3,flat,sector 92,1.60,3.0,4.0,3+,Relatively New,1615.0,1.0,0.0,1.0,High,Mid Floor,16000000.0,1.8,82,4,0.2
4,flat,sector 102,0.48,2.0,2.0,1,Relatively New,582.0,0.0,1.0,0.0,High,Mid Floor,4800000.0,1.8,82,4,0.2

In [78]:
# Annual rent estimate
df['estimated_annual_rent'] = df['price_rupees'] * (df['yield_pct'] / 100)

In [79]:
df['estimated_annual_rent']

0        147600.0
1        171000.0
2         57600.0
3        288000.0
4         86400.0
          ...
3549      66600.0
3550    1080000.0
3551     108000.0
3552    2790000.0
3553     320400.0
Name: estimated_annual_rent, Length: 3554, dtype: float64

Step 3.2: Annual Operating Costs (Realistic)

Cost Item 	Value	Source/Logic

Maintenance	--- ‚Çπ2/sqft/month	Standard Gurgaon builder rate

Property Tax----	‚Çπ1/sqft/month	MCG rates

Insurance---	‚Çπ8,000/year	ICICI/LIC average

Miscellaneous	---‚Çπ7,000/year	Utilities/marketing

In [80]:
# Annual maintenance (built-up area in sq ft)
df['maintenance'] = df['built_up_area'] * df['maint_rate'] * 12

# Annual property tax (based on property value)
df['property_tax'] = df['price_rupees'] * (df['tax_rate_pct'] / 100)

In [81]:
# Step 5: Constants used in calculations
down_payment_pct = 20  # %
loan_interest = 8.5 / 100
loan_term_years = 20
insurance = 8000
misc_expenses = 7000

In [82]:
# EMI = P √ó r √ó (1+r)^n / ((1+r)^n ‚Äì 1)
#  P: Loan amount,  r: Monthly interest rate,  n: Number of months

def calculate_emi(principal, annual_rate, years):
    r = annual_rate / 12
    n = years * 12
    emi = (principal * r * (1 + r) ** n) / ((1 + r) ** n - 1)
    return emi

In [83]:
def compute_roi(row):
    price = row['price_rupees']
    annual_rent = row['estimated_annual_rent']
    occupancy = row['occupancy_rate']

    # Loan amount (80% of price)
    loan_amount = price * (1 - down_payment_pct / 100)

    # EMI and Annual EMI
    emi = calculate_emi(loan_amount, loan_interest, loan_term_years)
    annual_emi = emi * 12

    # Total expenses
    total_expenses = row['maintenance'] + row['property_tax'] + insurance + misc_expenses

    # Effective annual rent (adjusted by occupancy)
    effective_rent = annual_rent * (occupancy / 100)

    # Cashflow and ROI
    annual_cash_flow = effective_rent - annual_emi - total_expenses
    total_investment = price * (down_payment_pct / 100) + total_expenses
    roi = (annual_cash_flow / total_investment) * 100

    return pd.Series({
        'EMI': round(emi),
        'Annual_Cashflow': round(annual_cash_flow),
        'ROI (%)': round(roi, 2)
    })

In [84]:
df[['EMI', 'Annual_Cashflow', 'ROI (%)']] = df.apply(compute_roi, axis=1)

In [87]:
df.sample(10)

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,...,yield_pct,occupancy_rate,maint_rate,tax_rate_pct,estimated_annual_rent,maintenance,property_tax,EMI,Annual_Cashflow,ROI (%)
761,flat,sector 59,3.90,3.0,1.0,0,Under Construction,2295.0,0.0,0.0,...,1.8,82,4,0.2,702000.0,110160.0,78000.0,270761.0,-2876650.0,-35.94
1806,house,sector 109,6.25,4.0,4.0,3+,Relatively New,5400.0,1.0,0.0,...,1.8,82,4,0.2,1125000.0,259200.0,125000.0,433912.0,-4683639.0,-36.31
1592,house,sector 24,2.75,7.0,7.0,3+,Moderately Old,3000.0,0.0,0.0,...,1.8,82,4,0.2,495000.0,144000.0,55000.0,190921.0,-2099153.0,-36.74
3277,flat,sector 84,0.84,3.0,3.0,3+,New Property,1561.0,0.0,0.0,...,1.8,82,4,0.2,151200.0,74928.0,16800.0,58318.0,-682557.0,-38.20
860,flat,sector 102,1.39,3.0,3.0,3,Relatively New,1493.0,1.0,0.0,...,1.8,82,4,0.2,250200.0,71664.0,27800.0,96502.0,-1067323.0,-36.87
3494,flat,sector 99,1.60,3.0,3.0,3,Under Construction,1810.0,0.0,0.0,...,1.8,82,4,0.2,288000.0,86880.0,32000.0,111081.0,-1230696.0,-36.91
44,house,sector 13,1.25,3.0,6.0,2,Old Property,115.0,0.0,0.0,...,1.8,82,4,0.2,225000.0,5520.0,25000.0,86782.0,-902408.0,-35.45
223,flat,sohna road,0.45,2.0,2.0,2,Relatively New,789.0,0.0,0.0,...,1.8,82,4,0.2,81000.0,37872.0,9000.0,31242.0,-370352.0,-38.50
1950,flat,sector 109,1.70,3.0,3.0,3,Relatively New,1550.0,0.0,0.0,...,1.8,82,4,0.2,306000.0,74400.0,34000.0,118024.0,-1288768.0,-36.58
3101,flat,sector 70,1.75,3.0,5.0,3,New Property,1527.0,1.0,0.0,...,1.8,82,4,0.2,315000.0,73296.0,35000.0,121495.0,-1322939.0,-36.51

In [88]:
df['EMI']

0         56929.0
1         65955.0
2         22216.0
3        111081.0
4         33324.0
          ...
3549      25688.0
3550     416555.0
3551      41656.0
3552    1076101.0
3553     123578.0
Name: EMI, Length: 3554, dtype: float64

In [89]:
# Step 9: Final output preview
final_cols = ['price', 'built_up_area', 'estimated_annual_rent', 'EMI',
              'maintenance', 'property_tax', 'Annual_Cashflow', 'ROI (%)']

In [90]:
df[final_cols].head()

,price,built_up_area,estimated_annual_rent,EMI,maintenance,property_tax,Annual_Cashflow,ROI (%)
0,0.82,850.0,147600.0,56929.0,40800.0,16400.0,-634318.0,-37.05
1,0.95,1226.0,171000.0,65955.0,58848.0,19000.0,-744083.0,-37.34
2,0.32,1000.0,57600.0,22216.0,48000.0,6400.0,-288763.0,-40.71
3,1.60,1615.0,288000.0,111081.0,77520.0,32000.0,-1221336.0,-36.74
4,0.48,582.0,86400.0,33324.0,27936.0,9600.0,-381581.0,-37.69

In [49]:
df.sample(10)

,property_type,sector,price,bedRoom,bathroom,balcony,agePossession,built_up_area,servant room,store room,...,yield_pct,occupancy_rate,maint_rate,tax_rate,estimated_annual_rent,maintenance,property_tax,EMI,Annual_Cashflow,ROI (%)
2668,flat,sector 86,1.30,2.0,3.0,3,Relatively New,944.0,0.0,0.0,...,2.5,88,2,1.0,0.03250,22656.0,11328.0,90254.0,-1132027.0,-42.73
3292,flat,sector 80,1.40,3.0,4.0,2,Moderately Old,1922.0,1.0,0.0,...,2.5,88,2,1.0,0.03500,46128.0,23064.0,97196.0,-1250546.0,-43.36
2909,flat,sector 9,1.25,4.0,3.0,3,Old Property,2007.0,1.0,0.0,...,2.5,88,2,1.0,0.03125,48168.0,24084.0,86782.0,-1128640.0,-43.62
2512,flat,sector 69,0.90,3.0,2.0,3,Relatively New,1473.0,0.0,0.0,...,2.5,88,2,1.0,0.02250,35352.0,17676.0,62483.0,-817827.0,-43.78
3375,flat,sector 79,1.45,2.0,2.0,3,Under Construction,1578.0,0.0,0.0,...,2.5,88,2,1.0,0.03625,37872.0,18936.0,100667.0,-1279818.0,-43.07
671,flat,sector 74,2.20,3.0,3.0,3,New Property,1826.0,0.0,0.0,...,2.5,88,2,1.0,0.05500,43824.0,21912.0,152737.0,-1913579.0,-42.71
22,flat,sector 2,0.60,1.0,1.0,1,Moderately Old,665.0,0.0,0.0,...,2.5,88,2,1.0,0.01500,15960.0,7980.0,41656.0,-538806.0,-43.49
1435,flat,sohna road,0.74,2.0,2.0,3+,Relatively New,1367.0,0.0,0.0,...,2.5,88,2,1.0,0.01850,32808.0,16404.0,51375.0,-680714.0,-44.08
83,house,sector 105,0.50,2.0,2.0,0,Moderately Old,100.0,0.0,0.0,...,2.5,88,2,1.0,0.01250,2400.0,1200.0,34713.0,-435155.0,-42.72
2876,flat,sector 30,1.30,3.0,3.0,2,Old Property,1401.0,0.0,0.0,...,2.5,88,2,1.0,0.03250,33624.0,16812.0,90254.0,-1148479.0,-43.09

In [94]:
df[['sector', 'price', 'bedRoom','built_up_area', 'estimated_annual_rent', 'Annual_Cashflow', 'ROI (%)']].to_csv("roi_analysis_file2.csv", index=False)

In [93]:
df1 = pd.read_csv('/content/real_estate_data - real_estate_data.csv')
df1.head()

,PropertyName,PropertySubName,NearbyLocations,LocationAdvantages,Link,PriceDetails,TopFacilities
0,Smartworld One DXP,"2, 3, 4 BHK Apartment in Sector 113, Gurgaon","['Bajghera Road', 'Palam Vihar Halt', 'DPSG Pa...","{'Bajghera Road': '800 Meter', 'Palam Vihar Ha...",https://www.99acres.com/smartworld-one-dxp-sec...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Salon', 'Restaurant', 'Spa'..."
1,M3M Crown,"3, 4 BHK Apartment in Sector 111, Gurgaon","['DPSG Palam Vihar Gurugram', 'The NorthCap Un...","{'DPSG Palam Vihar Gurugram': '1.4 Km', 'The N...",https://www.99acres.com/m3m-crown-sector-111-g...,"{'3 BHK': {'building_type': 'Apartment', 'area...","['Bowling Alley', 'Mini Theatre', 'Manicured G..."
2,Adani Brahma Samsara Vilasa,"Land, 3, 4 BHK Independent Floor in Sector 63,...","['AIPL Business Club Sector 62', 'Heritage Xpe...","{'AIPL Business Club Sector 62': '2.7 Km', 'He...",https://www.99acres.com/adani-brahma-samsara-v...,{'3 BHK': {'building_type': 'Independent Floor...,"['Terrace Garden', 'Gazebo', 'Fountain', 'Amph..."
3,Sobha City,"2, 3, 4 BHK Apartment in Sector 108, Gurgaon","['The Shikshiyan School', 'WTC Plaza', 'Luxus ...","{'The Shikshiyan School': '2.9 KM', 'WTC Plaza...",https://www.99acres.com/sobha-city-sector-108-...,"{'2 BHK': {'building_type': 'Apartment', 'area...","['Swimming Pool', 'Volley Ball Court', 'Aerobi..."
4,Signature Global City 93,"2, 3 BHK Independent Floor in Sector 93 Gurgaon","['Pranavananda Int. School', 'DLF Site central...","{'Pranavananda Int. School': '450 m', 'DLF Sit...",https://www.99acres.com/signature-global-city-...,{'2 BHK': {'building_type': 'Independent Floor...,"['Mini Theatre', 'Doctor on Call', 'Concierge ..."